In [1]:
import pandas as pd

dataset = pd.read_csv(r'C:\Desktop\PolicyBotAI\dataset\hr_policies.csv')

dataset.sample()

,policy_id,policy_name,category,subcategory,applicable_to,department,description,version,effective_date,review_cycle,approval_authority,is_mandatory,last_updated_year,details,related_form
260,1261,KPI Setting — Performance Management,Performance Management,KPI Setting,Permanent Employees,IT,Covers the probation period evaluation criteri...,v3.0,18/08/2023,Annual,CHRO,No,2023,"{""appraisal_cycle"": ""Bi-Annual"", ""rating_scale...",HR-F01

In [2]:
dataset.isnull().sum()

policy_id              0
policy_name            0
category               0
subcategory            0
applicable_to          0
department             0
description            0
version                0
effective_date         0
review_cycle           0
approval_authority     0
is_mandatory           0
last_updated_year      0
details                0
related_form          75
dtype: int64

In [3]:
dataset.drop(columns=['related_form', 'applicable_to'], inplace=True)

In [4]:
dataset.columns

Index(['policy_id', 'policy_name', 'category', 'subcategory', 'department',
       'description', 'version', 'effective_date', 'review_cycle',
       'approval_authority', 'is_mandatory', 'last_updated_year', 'details'],
      dtype='str')

In [5]:

dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   policy_id           500 non-null    int64
 1   policy_name         500 non-null    str
 2   category            500 non-null    str
 3   subcategory         500 non-null    str
 4   department          500 non-null    str
 5   description         500 non-null    str
 6   version             500 non-null    str
 7   effective_date      500 non-null    str
 8   review_cycle        500 non-null    str
 9   approval_authority  500 non-null    str
 10  is_mandatory        500 non-null    str
 11  last_updated_year   500 non-null    int64
 12  details             500 non-null    str
dtypes: int64(2), str(11)
memory usage: 221.5 KB

In [6]:
dataset.describe()

         policy_id  last_updated_year
count   500.000000         500.000000
mean   1250.500000        2022.478000
std     144.481833           1.104516
min    1001.000000        2021.000000
25%    1125.750000        2022.000000
50%    1250.500000        2022.000000
75%    1375.250000        2023.000000
max    1500.000000        2024.000000

In [7]:
dataset.isnull().sum()

policy_id             0
policy_name           0
category              0
subcategory           0
department            0
description           0
version               0
effective_date        0
review_cycle          0
approval_authority    0
is_mandatory          0
last_updated_year     0
details               0
dtype: int64

In [8]:
dataset.to_csv(r"C:\Desktop\PolicyBotAI\dataset/processed_policies.csv", index=False)